name: flutter_unity_widget
description: Flutter Unity 3D widget for embedding Unity game scenes in flutter. This library now supports Unity as a Library.
version: 3.0.3
#authors:
#  - Rex Raphael <rex.raphael@outlook.com>
#  - Thomas Stockx <thomas@stockxit.com>
#  - Kris Pypen <kris.pypen@gmail.com>
homepage: https://github.com/juicycleff/flutter-unity-view-widget/tree/master

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: 1.0.8
  plugin_platform_interface: 1.0.3
  stream_transform: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # TODO(iskakaushik): The following dependencies can be removed once
  # https://github.com/dart-lang/pub/issues/2101 is resolved.
  flutter_driver:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.xraph.plugins.flutterunitywidget
        pluginClass: FlutterUnityWidgetPlugin
      ios:
        pluginClass: FlutterUnityWidgetPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0"